/**/*:
  chimera_d_4:
    ros__parameters:
      coord_frame: enu_flu
      display_name: Chimera D4
      executable: vehicle
      frame_name: d4_base_link
      namespace: "/uas4/"
      location_topic: "/uas4/global_position/local"
      parent_frame: map
      platform: quad
      sensors:
        - two_axis_gimbal.yaml
      viz:
        - uas4_tba.yaml
