/**/*:
  uas4_tba:
    ros__parameters:
      name: uas4_tba
      display_name: UAS4 TargetBoxArray Viz
      executable: tba_viz
      localization_topic: /uas4/target_locations
      loc_viz_topic: /viz/uas4/tbas_recent
      loc_viz_topic_all: /viz/uas4/tbas_all
      map_ref: [32.5006765, -83.7512641, 100.75844396218884]