/**/*:
  d3_rangefinder:
    ros__parameters:
      display_name: Rangefinder (Gimbal, D3)
      executable: rangefinder
      frame_name: d3_rangefinder_frame
      offset:
        - 0.0
        - 0.025
        - 0.0
        - 0.0
        - 0.0
        - 0.0
      range_topic: /uas3/gimbal_lidar_50m
      parent_frame: d3_gimbal_frame
      sensor_type: rangefinder
