/**/*:
  two_axis_gimbal:
    ros__parameters:
      display_name: 2-Axis Gimbal (D4)
      frame_name: d4_gimbal
      offset:
        - 0.5
        - 0.0
        - -0.25
      coord_frame: ned-frd
      orientation_topic: /uas4/gimbal_control/device/attitude_status
      command_topic: /uas4/gimbal_control/manager/set_attitude
      parent_frame: d4_base_link
      body_orientation_topic: /uas4/global_position/local
      sensor_type: gimbal
