/**/*:
  two_axis_gimbal:
    ros__parameters:
      display_name: 2-Axis Gimbal (D4)
      frame_name: d4_gimbal_frame
      offset:
        - 0.5
        - 0.0
        - -0.25
      orientation_topic: /uas4/gimbal_control/device/attitude_status
      parent_frame: d4_base_link
      sensor_type: gimbal
