/**/*:
  two_axis_gimbal:
    ros__parameters:
      display_name: 2-Axis Gimbal (D4)
      executable: gimbal
      frame_name: d4_gimbal_frame
      offset:
        - 0.205
        - 0.0
        - -0.081
      coord_frame: ned-frd
      orientation_topic: /uas4/gimbal_control/device/attitude_status
      command_topic: /uas4/gimbal_control/manager/set_attitude
      body_orientation_topic: /uas4/global_position/local
      parent_frame: d4_base_link
      sensor_type: gimbal
      sensors:
        - rangefinder.yaml
