/**/*:
  narrow_cam:
    ros__parameters:
      display_name: RGB Camera (D3)
      executable: camera
      frame_name: d3_rgb
      offset:
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
      cam_info_topic: /uas3/camera/camera_info
      parent_frame: d3_gimbal_frame
      sensor_type: camera
